name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-24.04
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_TOKEN }}
        with:
          path-to-signatures: 'signatures.json'
          path-to-document: 'https://github.com/Duet3D/cla/blob/master/Duet3D%20Contributor%20License%20Agreement.pdf'
          remote-organization-name: 'Duet3D'
          remote-repository-name: 'cla'
          branch: 'master'

